---
# tasks file for nginx

- ansible.builtin.import_tasks: repository.yml

- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: apply nginx config template to /etc/nginx/conf.d/mattermost.conf
  ansible.builtin.template:
    src: mattermost.conf.j2
    dest: /etc/nginx/conf.d/mattermost.conf
  notify: restart nginx

- name: Allow nginx to connect to MatterMost
  ansible.builtin.command: setsebool httpd_can_network_connect true
  when: ansible_distribution == "RedHat"

- name: Change nginx cache directory permissions
  ansible.builtin.file:
    path: /var/cache/nginx
    state: directory
    owner: nginx
    group: nginx
    recurse: yes
  when: ansible_distribution == "RedHat"
  notify: restart nginx

- name: remove nginx default site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx
